linters:
  Indentation:
    enabled: true
    allow_non_nested_indentation: false
    character: space # or 'tab'
    width: 4

  PropertySortOrder:
    enabled: false
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
  
  ColorVariable:
    enabled: false

  ImportantRule:
    enabled: false

  ColorKeyword:
    enabled: false

  VendorPrefix:
    enabled: false

  IdSelector:
    enabled: false

  QualifyingElement:
    enabled: false